name: flare_loading
description: Loading widget based on a custom Flare animation, allow you to create beautiful custom loading widgets or dialogs
version: 3.0.0
homepage: https://github.com/jaumard/flare_loading
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.7.8 <2.0.0"

dependencies:
  flare_flutter:
    git:
      url: https://github.com/Lomski/Flare-Flutter # Repo
      path: ./flare_flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
